version: '2.1'
services:
  database:
    image: 'mysql:5.7'
    container_name: dev.api.db
    environment:
      MYSQL_ROOT_PASSWORD: sam
      MYSQL_DATABASE: sam
      MYSQL_USER: sam
      MYSQL_PASSWORD: sam
    ports:
      - '3306:3306'
    healthcheck:
      test: '/usr/bin/mysql --user=sam --password=sam --execute "SHOW DATABASES;"'
      interval: 5s
      timeout: 20s
      retries: 10
  aws-sam-local:
    image: cnadiminti/aws-sam-local
    command: 'local start-api --docker-volume-basedir "$PWD/" --host 0.0.0.0 --template template.dev.yml'
    ports:
      - '3000:3000'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './:/var/opt'
    environment:
      - 'DEBUG=sam-docker-api:*'
    container_name: dev.api
    depends_on:
      database:
        condition: service_healthy
    links:
      - 'database:db.master.local'
